

---- PRIMARY KEY CONSTRAINT IS UNIQUELY IDENTIFIED KEY  IT DOES NOT ALLOWS DUPLICATE VALUES ----
CREATE TABLE EMPLOYEE (
	ID INT PRIMARY KEY,
    ---- NOT NULL CONSTRAINT DOES NOT ALLOWS NULL VALUES ----
    EMP_NAME VARCHAR(100) NOT NULL,
    ---- UNIQUE CONSTRAINT ENSURES THAT ALL VALUES ARE DIFFERENT ----
    MOBILE BIGINT UNIQUE,
    ---- SETS DEFAULT VALUE WHEN NO VALUE SPECIFIED ----
    ADDRESS VARCHAR(100) DEFAULT "HYDERABAD"
    );
    
    DESC EMPLOYEE;
    
    INSERT INTO EMPLOYEE VALUES (1,"VMANOJ",787487252,"SURYAPET");
	INSERT INTO EMPLOYEE VALUES (2,"RAVI",8106444512,"VIZAG");
    ---- THE ADRESS IS SET "HYDERABAD" DEFAULT ----
	INSERT INTO EMPLOYEE(ID,EMP_NAME,MOBILE) VALUES (3,"HARI",701345056);
    
	SELECT * FROM EMPLOYEE;
    
    CREATE TABLE EMPLOYEE2(
		ID INT PRIMARY KEY AUTO_INCREMENT,
        NAME VARCHAR(100) NOT NULL DEFAULT "NAME",
        MOBILE BIGINT UNIQUE,
        ADDRESS VARCHAR(100) DEFAULT "HYD"
        );
        
        
    INSERT INTO EMPLOYEE2(ID,MOBILE) VALUES(111,987648376);
    ---- ID IS AUTOMATICALLY INCREASE IF NOT SPECIFIED ----
    INSERT INTO EMPLOYEE2(NAME,MOBILE) VALUES("RAJESH",874620486);
    INSERT INTO EMPLOYEE2(NAME,MOBILE) VALUES("BABBLU",83264928762);
    
    SELECT * FROM EMPLOYEE2
    INSERT INTO EMPLOYEE2(MOBILE) VALUES(87326843);
    
    
    CREATE TABLE EMPLOYEE3(
    ---- ID IS START FROM 1 AUTOMATICALLY  INCREASE IF NOT SPECIFIED ----
		ID INT PRIMARY KEY AUTO_INCREMENT,
        NAME VARCHAR(100) NOT NULL,
        AGE INT NOT NULL,
        SALARY INT NOT NULL,
        MOBILE BIGINT UNIQUE,
        
        ---- CHECK ENSURES THAT THE VALUES IN A COLUMN SATISFIES A SPECIFIC CONDITION -----
        CHECK ((AGE>=18) AND (SALARY>=10000))
        );
        
        INSERT INTO EMPLOYEE3(NAME,AGE,SALARY,MOBILE) VALUES("MANOJ",22,200000,8106444512);
        SELECT * FROM EMPLOYEE3;
        
        INSERT INTO EMP1(NAME,AGE,SALARY,MOBILE) VALUES("MANOJ",27,10000,48972435);
        
        INSERT INTO EMPLOYEE3(ID,NAME,AGE,SALARY,MOBILE) VALUES(2,"HARI",27,10000,956822435);
        
		INSERT INTO EMPLOYEE3(NAME,AGE,SALARY,MOBILE) VALUES("RAKESH",25,10000,99489896);
		
        ---- IT DOES NOT ALLOW BECAUSE IT DOES NOT SATISFY CHECK CONDITION ----
        INSERT INTO EMPLOYEE3(NAME,AGE,SALARY,MOBILE) VALUES("VIKRAM",17,10000,99836878763);