
CREATE TABLE EMPLOYEES(
	ID INT,
    NAME VARCHAR(100),
    JOINING_DATE DATE)
    ---- DATE IN "YYYY-MM-DD" FORMAT ----
    INSERT INTO EMPLOYEES VALUES(111,"MANOJ","2024-07-20"),(112,"RAVI","2024-07-23")
    
    SELECT * FROM EMPLOYEES
    ---- USED TO PRINT CURRENT DATE ----
    SELECT CURRENT_DATE
    SELECT CURDATE
    
    ----  USED TO ADD DAYS, MONTH AND YEAR TO DATE ----
    SELECT ADDDATE("2000-03-07",INTERVAL 2 YEAR) AS YEARS
    SELECT ADDDATE("2000-03-07",INTERVAL 5 MONTH) AS MONTHS
    SELECT ADDDATE("2000-03-07",INTERVAL 3 DAY) AS DAYS
    
    ---- ADDING DATE ON TABLE ----
	SELECT ADDDATE(JOINING_DATE,INTERVAL 3 DAY) AS DAYS FROM EMPLOYEES WHERE NAME="MANOJ"
    SELECT ADDDATE(JOINING_DATE,INTERVAL 5 MONTH) AS MONTHS FROM EMPLOYEES WHERE ID=111
    SELECT ADDDATE(JOINING_DATE,INTERVAL 2 YEAR) AS YEARS FROM EMPLOYEES
    
    ---- ADD,SUB,DIFF ON DATE ---
    SELECT ADDDATE("2000-05-20","2000-02-02") AS NEWDATE
    SELECT SUBDATE("2000-05-20","2000-02-02") AS NEWDATE
    SELECT DATEDIFF("2000-05-20","2000-02-02") AS NEWDATE
    ---- DIFFENCE BETWEEN DATES IN TABLE DATA ----
	SELECT DATEDIFF(CURRENT_DATE,JOINING_DATE) AS NEWDATE FROM EMPLOYEES WHERE ID=111
    SELECT DATEDIFF(CURRENT_DATE,JOINING_DATE) AS NEWDATE FROM EMPLOYEES WHERE ID=112
  
    
CREATE TABLE INTERNS(
	ID INT,
    LOGIN TIME,
    LOGOUT TIME);
    ---- TIME IN "HH:MM:SS:" FORMAT ----
    INSERT INTO INTERNS VALUES(101,"10:05:45","17:07:30"), (102,"09:55:20","17:01:36")
    SELECT * FROM INTERNS
    
    ---- USED TO PRINT CURRENT TIME ----
	SELECT CURRENT_TIME()
	SELECT CURTIME()
    ---- ADD, SUB, DIFF ON TIME  ----
    SELECT ADDTIME(CURRENT_TIME,LOGIN) AS TOTAL FROM INTERNS 
    SELECT SUBTIME(LOGOUT,LOGIN)AS TOTAL FROM INTERNS WHERE ID=101
	SELECT TIMEDIFF(LOGOUT,LOGIN)AS TOTAL FROM INTERNS WHERE ID =102
    
    SELECT ADDTIME("20:12:40","12:15:44") AS TOTAL
    SELECT SUBTIME("20:12:40","12:15:44") AS TOTAL
    SELECT TIMEDIFF("20:12:40","12:15:44") AS DIFF
    
    ---- TIME CONVERSION ----
    SELECT TIME_TO_SEC(TIMEDIFF(LOGOUT,LOGIN)) AS SECONDS FROM INTERNS
	SELECT TIME_TO_SEC("20:12:40") AS SECONDS
    
    CREATE TABLE DETAILS(
		ID INT, 
        ---- IT WILL TAKE CURRENT_TIMESTAMP AND NO CHANGE WHEN  UPDATE  ----
        CHECKIN TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        
        ---- IT WILL TAKE CURRENT_TIMESTAMP AND CHANGES  WILL HAPPEND WHEN  UPDATE  CURRENT_TIMESTAMP IS TAKES ----
        CHECKOUT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
        )
		
        INSERT INTO DETAILS VALUES(111,"2024-07-22 10:45:44","2024-07-23 22:30:44")
        INSERT INTO DETAILS VALUES(112,"2024-07-22 11:25:44","2024-07-23 18:55:46")
        SELECT * FROM DETAILS
        
        SET SQL_SAFE_UPDATES=0
        
          ---- CHECKOUT TIMESTAMP WILL BE CHANGED AS CURRENT_TIMESTAMP WHEN UPDATE HAPPENS ----
		UPDATE DETAILS SET ID=101 WHERE	ID=111	
        SELECT * FROM DETAILS
        
        UPDATE DETAILS SET ID=102 WHERE ID=112
        SELECT * FROM DETAILS
        
    
    
    
				
	