CREATE DATABASE OPERATORS
USE OPERATORS
CREATE TABLE INTERNS_DETAILS(ID INT,I_NAME VARCHAR(100),SALARY INT,PRESENT_DAYS INT, ABSENT_DAYS INT); 
INSERT INTO INTERNS_DETAILS VALUES(111,"MANOJ",15000,25,2),(112,"VINOD",20000,26,1),(113,"HARI",25000,22,5),(114,"SAI",30000,23,4),(115,"CHINNA",40000,20,7);
SELECT * FROM INTERNS_DETAILS

SELECT ID,I_NAME,(PRESENT_DAYS+0) AS ADDTION FROM INTERNS_DETAILS
SELECT ID,I_NAME,(30-PRESENT_DAYS) AS SUBSTRACTION FROM INTERNS_DETAILS
SELECT ID,I_NAME,(ABSENT_DAYS * 250) AS MULTIPLICATION FROM INTERNS_DETAILS
SELECT ID,I_NAME,(SALARY/PRESENT_DAYS) AS DIVISION FROM INTERNS_DETAILS
SELECT ID,I_NAME,(SALARY%PRESENT_DAYS) AS MODULO FROM INTERNS_DETAILS


SELECT * FROM INTERNS_DETAILS WHERE SALARY>20000;
SELECT * FROM INTERNS_DETAILS WHERE SALARY<20000;
SELECT * FROM INTERNS_DETAILS WHERE SALARY=30000;
SELECT * FROM INTERNS_DETAILS WHERE SALARY>=15000;
SELECT * FROM INTERNS_DETAILS WHERE SALARY<=20000;
SELECT * FROM INTERNS_DETAILS WHERE SALARY!=15000;



SELECT * FROM INTERNS_DETAILS WHERE SALARY>20000 AND PRESENT_DAYS>20
SELECT * FROM INTERNS_DETAILS WHERE SALARY<20000 OR  PRESENT_DAYS>26
SELECT * FROM INTERNS_DETAILS WHERE NOT SALARY=20000; 


SELECT * FROM INTERNS_DETAILS WHERE ABSENT_DAYS IS NOT NULL;
SELECT * FROM INTERNS_DETAILS WHERE ABSENT_DAYS IS NULL;

SELECT * FROM INTERNS_DETAILS WHERE SALARY BETWEEN 20000 AND 30000;
SELECT * FROM INTERNS_DETAILS WHERE SALARY IN (15000,40000);
SELECT *,
CASE
WHEN SALARY<=20000 THEN 2000
WHEN  SALARY>=20000 THEN 3000
END AS BONUS
FROM INTERNS_DETAILS




