CREATE TABLE EMPLOYEEE(ID INT PRIMARY KEY AUTO_INCREMENT,F_NAME VARCHAR(100),L_NAME VARCHAR(100),ADDRESS VARCHAR(100))
INSERT INTO EMPLOYEEE VALUES(111,"MANOJ","VANAPARTHY","HYDERABAD")
DESC EMPLOYEEE
SELECT * FROM EMPLOYEEE
INSERT INTO EMPLOYEEE(F_NAME,L_NAME,ADDRESS) VALUES("CHINNA","VANAPARTHY","HYDERABAD")
INSERT INTO EMPLOYEEE(F_NAME,L_NAME,ADDRESS) VALUES("VARUN","PADHI","VIJAYANAGARAM")
INSERT INTO EMPLOYEEE(F_NAME,L_NAME,ADDRESS) VALUES("SHIREESH","MALLESH","VIJAYANAGARAM")

SELECT * FROM EMPLOYEEE

---- CONCATENATION OF TWO TWO COLUMNS(HAVING STRING VALUES)----
SELECT F_NAME,L_NAME,CONCAT(L_NAME,," ",F_NAME) AS E_NAME FROM EMPLOYEEE  

---- CONACTENATION WITH SEPARATION ----
SELECT F_NAME,ADDRESS, CONCAT_WS(" / ",F_NAME,ADDRESS) AS ENAMEADDRESS FROM EMPLOYEEE

---- CONVERTING THE STRING INTO LOWERCASE ----
SELECT *,LOWER(ADDRESS) FROM EMPLOYEEE

---- CONVERTING THE STRING INTO UPPERCASE ----
SELECT *,UPPER(ADDRESS) FROM EMPLOYEEE

---- FINDING  THE  LENGTH OF STRING  ----
SELECT *, LENGTH(ADDRESS) AS ADDRESS FROM EMPLOYEEE

---- FINDING THE NO.OF CHARACTERS IN THE STRING ----
SELECT *, CHAR_LENGTH(ADDRESS) AS CHAR_ADDRESS FROM EMPLOYEEE

---- EXTRACTING THE PORTION (SUBSTRING ) FROM GIVEN STRING----
SELECT L_NAME, SUBSTRING(L_NAME,1,1) FROM EMPLOYEEE

 ---- EXTRACTING THE SUBSTRING AND CONCATENATE TO ANOTHER STRING ----
SELECT F_NAME,L_NAME, CONCAT( SUBSTRING(L_NAME,1,1),". ",F_NAME) AS E_NAME FROM EMPLOYEEE

----- IT REVERSE THE ORDER OF THE CHARACTERS IN THE STRING -----
SELECT ADDRESS, REVERSE(ADDRESS) FROM EMPLOYEEE

---- REPLACE IS USED TO UPDATE THE STRING ----
SELECT L_NAME, REPLACE (L_NAME,"VANAPARTHY","VANAPARTHI")  AS UPDATE1 FROM EMPLOYEEE

---- LIKE IS USED TO SEARCH THE SPECIFIC PATTERN IN COLUMN ----
---- PATTERNS END WITH I WILL RETURNS ----
SELECT * FROM EMPLOYEEE WHERE L_NAME LIKE "%I"

---- PATTERNS START WITH V WILL RETURNS---
SELECT * FROM EMPLOYEEE WHERE L_NAME LIKE "V%"

----  USED FOR FIXED LENGTH OF SEARCH PATTERN ----
SELECT * FROM EMPLOYEEE WHERE L_NAME LIKE "M___E__"







